name: vince-cart-management-build

on:
  push:
#     branches: [ "Master" ]
#   pull_request:
#     branches: [ "Master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: acrvinceproduse2001.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build ./src/Backend/vince-cart-management/ -t acrvinceproduse2001.azurecr.io/vincecartmanagement:${{ github.sha }}
        docker push acrvinceproduse2001.azurecr.io/vincecartmanagement:${{ github.sha }}
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Helm
        path: |
          ./Deploy/K8s/helm/backend-api

