name: Docker Image CI

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: vince.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        context: /vince/src/Backend/vince-cart-management/
    - run: |
        docker build . -t vince.azurecr.io/vincecartmanagement:${{ github.sha }}
        docker push cvince.azurecr.io/vincecartmanagement:${{ github.sha }}
