name: Docker Image CI

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: vince.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build ./src/Backend/vince-cart-management/ -t vince.azurecr.io/vincecartmanagement:${{ github.sha }}
        docker push cvince.azurecr.io/vincecartmanagement:${{ github.sha }}
