name: package-npm

on: 
   push:
     branches: [ "npmpackage-patch-1" ]
#   pull_request:
#     branches: [ "Master" ]
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm cache clean --force
      - run: |
          ls
          cd source
          ls
      - run: npm ci 
      - name: publish to github
        run: |
          npm config set registry https://npm.pkg.github.com
          npm set //npm.pkg.github.com/:_authToken ${{env.NODE_AUTH_TOKEN}}
          npm run publish:github
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#      - run: npm publish --registry https://npm.pkg.github.com
#       --prefix ./vince/Source/Backend/vince-cart-management/
