name: Publish Package

on: 
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm install --prefix ./Source/Backend/vince-cart-management/
      - run: npm run build --prefix ./Source/Backend/vince-cart-management/
      - run: npm publish --prefix ./Source/Backend/vince-cart-management/
