name: Publish Package

on:
    push:
      branches: [ "npmpackage-patch-1" ]
#   pull_request:
#     branches: [ "npmpackage-patch-1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to GitHub Packages
        run: npm login --registry=https://npm.pkg.github.com
      - name: Publish Package
        run: npm publish
