name: node_app_packages

on: 
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm cache clean --force
      - run: npm ci 
      - run: |
           ls       
      - run: npm publish --registry https://npmjs.com/org/node_app_packages
#       --prefix ./vince/Source/Backend/vince-cart-management/
