name: vince-cart-management-api-build

on:
  # push:
  #   branches: [ "Master" ]
  # pull_request:
  #   branches: [ "Master" ]
  workflow_dispatch:
env:
  AZURE_CONTAINER_REGISTRY: "acrvinceproduse2001.azurecr.io"
  CONTAINER_NAME: "vince-cart-management"
  RESOURCE_GROUP: "rg-vince-prod-use2-001"
  CLUSTER_NAME: "aks-vince-prod-use2-001"
  CHART_PATH: "./Deploy/K8s/helm/backend-api/charts"
  CHART_OVERRIDE_PATH: "./Deploy/K8s/helm/backend-api/charts/values.yaml"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v2
      
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  
          
      - uses: azure/docker-login@v1
        with:
          login-server: acrvinceproduse2001.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build ./Source/Backend/vince-cart-management/ -t acrvinceproduse2001.azurecr.io/vincecartmanagement:${{ github.sha }}
          docker push acrvinceproduse2001.azurecr.io/vincecartmanagement:${{ github.sha }}
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [buildImage]
#     if: success() && github.ref == 'refs/heads/Master'
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      # Runs Helm to create manifest files
      - name: Bake deployment
        uses: azure/k8s-bake@v2
        with:
          renderEngine: "helm"
          helmChart: ${{ env.CHART_PATH }}
          overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
          overrides: |
            replicaCount:3
          helm-version: "latest"
        id: bake

      # Deploys application based on manifest files from previous step
      - name: Deploy application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
    

